### ISSUE TITLE
can't start an app

### ISSUE THREAD

**Issue by Denisolt** [VulcanJS/Vulcan-Starter#10]
hey, completely new to Meteor and Node. I was following your setup, but I keep getting the same error. Running it on OS X 10.13
![screen shot 2018-01-30 at 19 22 02](https://user-images.githubusercontent.com/17182033/35598677-e00f2810-05f2-11e8-82c9-bb94694b3d69.png)

Thank you in advance.

**Comment by SachaG** [comment]
Someone else reported the same error, they said re-cloning the repo helped?

**Comment by liamr** [comment]
I'm getting the same, even after re-cloning. 10.13 too.

**Comment by SachaG** [comment]
I'm not sure what the issue is yet but I suspect it has to do with Meteor 1.6.1. Maybe this can help?

https://blog.meteor.com/announcing-meteor-1-6-1-50aad71da4e6

I'll try to find some time to do more testing soon.

**Comment by SachaG** [comment]
Another fix might be switching to the 2-repo setup: http://docs.vulcanjs.org/#Two-Repo-Install-Optional

This way you can run the `devel` branch of the core repo and be sure to have the most up-to-date code.

**Comment by Denisolt** [comment]
The issue was solved by cloning the repo again. Magically worked. Good luck @liamr 
One note tho, first time I have cloned the repo into my projects folder and it failed. Later, I re-cloned it to Home directory (literally `cd` and cloned again) and it worked. hope this helps
