### ISSUE TITLE
Modals not showing in example-forum

### ISSUE THREAD

**Issue by cmacom** [VulcanJS/Vulcan-Starter#111]
Just got the example-forum running, but when clicking on the New Post button nothing happened.  I saw the [fix](https://github.com/VulcanJS/Vulcan-Starter/commit/437358dba69366e83f39df3f5687e8f3c0d2afd8) to the Getting-Starter app where you updated the _bootstrap.scss so copied that into the example-forum and linked it up.  It did get the dropdowns working but the modal still didn't show (although at least the screen greys out now).  Any ideas/updates to get it working again?

**Comment by jasonmarkperez** [comment]
Same with the instagram example, modal doesn't display.

**Comment by yairtal** [comment]
Try cloning the repo again and then:
`meteor update`
`yarn install`
`yarn start`

**Comment by cmacom** [comment]
Thank you latest fix worked.
