### ISSUE TITLE
Error: Cannot find module 'react-bootstrap/Form'

### ISSUE THREAD

**Issue by oskareke** [VulcanJS/Vulcan-Starter#114]
Getting this error after running npm start:
`Error: Cannot find module 'react-bootstrap/Form'`

**Comment by eric-burel** [comment]
Hi, please update your packages, it should be fixed in react-bootstrap beta 5

**Comment by Utkarshnamdeo** [comment]
Hi please fix the issue. It exits with code 1.

**Comment by eric-burel** [comment]
@Utkarshnamdeo can you confirm your react-bootstrap version ? You can run `npm list react-bootstrap`. It should be `1.0.0-beta.5`.
This bug is not in Vulcan, it is a regression in react-bootstrap beta 3 which is already solved in beta 5.

**Comment by oskareke** [comment]
I was getting this error after a fresh clone and install with 1.0.0-beta.5, but running npm update somehow fixed it.

**Comment by Utkarshnamdeo** [comment]
@eric-burel Thanks Eric, That solved the problem. Indeed it wasn't a Vulcan issue.
