### ISSUE TITLE
Bug in Example-Form - Expected type Date for field “Date”, received “2019-02-21T13:00:00.000Z” instead

### ISSUE THREAD

**Issue by bseng** [VulcanJS/Vulcan-Starter#118]
Hi,

I'm adopting example-form nested techniques in my own code and add a new date field in the address schema.

The proper input display but after I picked a date and try to save it give me an error saying.

Expected type Date for field “Date”, received “2019-02-21T13:00:00.000Z” instead

How should I get the date to work?
Thanks

**Comment by SachaG** [comment]
With a normal form at least date fields do seem to be stored as dates (when inspecting the state of the `SmartForm` component). So maybe this is an issue specific to nested forms? Could you see if you get the same issue when the date field is not nested but instead at the root of the document?

**Comment by bseng** [comment]
I've use the date field in the normal schema (vulcan one) on root level and it works.

**Comment by SachaG** [comment]
I'm not sure… but can you open a new issue on the main repo about this? https://github.com/VulcanJS/Vulcan/issues

**Comment by bseng** [comment]
sure

**Comment by bseng** [comment]
Created a new issue in [main repo](https://github.com/VulcanJS/Vulcan/issues/2211)

**Comment by eric-burel** [comment]
See https://github.com/VulcanJS/Vulcan/issues/2211. This issue will be resolved when we handle nested schemas, probably in the next release.

Closing because this repo is only for the starter itself.
