### ISSUE TITLE
Bug in example-forum, example-forms and example-movies: delete function does not work

### ISSUE THREAD

**Issue by ShaLi2204** [VulcanJS/Vulcan-Starter#119]
Hi there, 

in the example-forum, when trying to delete a post from my own, the following error message shows up: cannot convert undefined or null to object. Could you please check it? Thanks a lot in advance!

**Comment by ShaLi2204** [comment]
Update: I have checked it around. It seems that delete function does not work in all of the three examples mentioned above. However, I think a few weeks before, the delete function did work. Is it due to some update in the vulcanjs version? Could you please kindly fix it? Thank you so much in advance.

**Comment by ShaLi2204** [comment]
Hi, 

any update on this issue?

**Comment by eric-burel** [comment]
Hi, I've managed to reproduce this issue. It may just be an UI issue, I don't know yet.

**Comment by eric-burel** [comment]
Closing because I don't have this issue on the latest "devel" branch.
