### ISSUE TITLE
Bug in example-forum version 1.12.12

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#123]
Hi,

I tested with the default project package:
example-forum        added, version 1.12.12   
reactive-dict        added, version 1.2.1
session              added, version 1.2.0
vulcan:accounts      added, version 1.13.0
vulcan:admin         added, version 1.13.0
vulcan:embed         added, version 1.13.0
vulcan:events        added, version 1.13.0
vulcan:forms         added, version 1.13.0
vulcan:newsletter    added, version 1.13.0
vulcan:redux         added, version 1.12.8
vulcan:ui-bootstrap  added, version 1.13.0
vulcan:voting        added, version 1.13.0

When I run, I got the following errors:
W20190330-09:33:21.990(1)? (STDERR) Trying to replace non-registered component FormElement. The component is being registered. If you were trying to replace a component defined by another package, make sure that you haven't misspelled the name. Check also if the original component is still being registered or that it hasn't been renamed.
W20190330-09:33:22.054(1)? (STDERR) /home/kauprey/.meteor/packages/meteor-tool/.1.8.0_2.123t72a.uiqe++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190330-09:33:22.054(1)? (STDERR) 						throw(ex);
W20190330-09:33:22.054(1)? (STDERR) 						^
W20190330-09:33:22.054(1)? (STDERR) 
W20190330-09:33:22.055(1)? (STDERR) ReferenceError: FRC is not defined
W20190330-09:33:22.055(1)? (STDERR)     at SearchForm.jsx (packages/example-forum/lib/components/common/SearchForm.jsx:8:15)
W20190330-09:33:22.055(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190330-09:33:22.055(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190330-09:33:22.055(1)? (STDERR)     at Module.moduleLink [as link] (/home/kauprey/.meteor/packages/modules/.0.13.0.1b9i0ki.qiyp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)

Please help.

Thank You
Adalidda

**Comment by jdowning100** [comment]
Please see my PR https://github.com/VulcanJS/Vulcan-Starter/pull/124

**Comment by adalidda** [comment]
Thank You @jdowning100
