### ISSUE TITLE
latest example-forum bug: Error: There is already a collection named "cronHistory"

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#131]
Hi Sacha,

I just git clone the latest version of Vulcan Starter example-forum. When I npm install and npm start, I got the following error:
W20190913-21:01:02.142(7)? (STDERR) /home/kauprey/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20190913-21:01:02.142(7)? (STDERR)       throw error;
W20190913-21:01:02.143(7)? (STDERR)       ^
W20190913-21:01:02.143(7)? (STDERR) 
W20190913-21:01:02.143(7)? (STDERR) Error: There is already a collection named "cronHistory"
W20190913-21:01:02.143(7)? (STDERR)     at new Collection (packages/mongo/collection.js:122:15)
W20190913-21:01:02.143(7)? (STDERR)     at packages/littledata_synced-cron.js:113:28
W20190913-21:01:02.143(7)? (STDERR)     at Function.time (/home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/profile.js:309:28)
W20190913-21:01:02.144(7)? (STDERR)     at /home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:427:13
W20190913-21:01:02.144(7)? (STDERR)     at /home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:472:5
W20190913-21:01:02.144(7)? (STDERR)     at Function.run (/home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/profile.js:510:12)
W20190913-21:01:02.144(7)? (STDERR)     at /home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1

How can I fix it ?

By the way, there are a lot of new things since your latest blog of March 29, 2019. When can we expect a new blog ?

Thank You
Adalidda

**Comment by adalidda** [comment]
Hi,

I found that this bug is fixed by editing the example-forum/package.js

and change

'percolatestudio:synced-cron',

to

//    'percolatestudio:synced-cron',

Thank You
Adalidda

**Comment by eric-burel** [comment]
It has been replaced by littledata:synced-cron. This will be fixed in the next release of the starter.

**Comment by adalidda** [comment]
Thank You @eric-burel
