### ISSUE TITLE
Issue with the latest Vulcan-Starter

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#137]
Hi,

When I run npm start
I got the following error:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

And I don't know if it's related but in all my code where I use javascript String slice() method, I got error

TypeError: Cannot read property 'slice' of undefined

I have deleted npm cache but still got the same issue. I can't understand why.

Thank You
Adalidda

**Comment by adalidda** [comment]
I think that this version is not yet ready for version 1.14.0. Will wait for the next update.

**Comment by Apollinaire** [comment]
FYI the npm warnings about fsevents are normal. They just say "We did not install fsevents because it only works on macOs and you are on Linux".
