### ISSUE TITLE
step 12 displayName not displayed

### ISSUE THREAD

**Issue by DylanKojiCheslin** [VulcanJS/Vulcan-Starter#138]
on the "devel" branch on step 12 the displayName is never shown and the following steps don't render as intended.  

seen on a two repo installation with both on "devel" branch at 1.14.0 
OS: Ubuntu 18.04.3 LTS  

bug example repo: https://github.com/DylanKojiCheslin/step12Bug

**Comment by DylanKojiCheslin** [comment]
https://github.com/DylanKojiCheslin/step12Bug/blob/devel/Screenshot%20from%202019-11-20%2006-42-22.png

**Comment by loustak** [comment]
Same problem here, no errors and warnings in the console.

**Comment by eric-burel** [comment]
Sorry I try to repro based on your code but I am stuck at `"Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>"`.

I just updated the starter master branch so 2 repo install is not necessary to test, I just run the app as a 1-repo install

**Comment by eric-burel** [comment]
I don't have this message on a fresh starter install (but I did not actually test your issue on step 12 yet)

**Comment by DylanKojiCheslin** [comment]
I tried this on a devel 1-repo setup and it had the same behavior Vulcan 1.14.0, Ubuntu 18.04.3 LTS . 

in both cases (1 & 2 repo) I had to manually installed babel with "meteor npm install --save @babel/runtime" due to an error saying bcrypt wasn't installing (this is specfic to Ubuntu afaik). I also have run "npm audit fix" on both so either could be causing the issues that @eric-burel was seeing on my repo but not on the fresh install. Din't see the error He mentioned, it may be related to having different OS?

I will try a 1-repo without the "npm audit fix" but halve to do the manual babel install, as it won't build otherwise.

**Comment by eric-burel** [comment]
Ok I've managed to do a repro.
@SachaG I think you wanted the `hasOne` relation to be implicit, using `collection.js` `addAutoRelations` function, but it is not yet used according to your comment. So we need to explicitely add `relation: "hasOne"` to the field name. Will PR.

**Comment by eric-burel** [comment]
Can you please check that the change I made in https://github.com/VulcanJS/Vulcan-Starter/pull/143 fixes step 12 for you, so I can close this issue?

**Comment by DylanKojiCheslin** [comment]
It works, thank you.
