### ISSUE TITLE
`onInsert` property not present in schema

### ISSUE THREAD

**Issue by jamesmillerburgess** [VulcanJS/Vulcan-Starter#14]
Great tutorial! Very interactive and easy to follow. 👍 

I just found one issue that isn't already reported on this repo:

**Step 5:** *"Note that* `createdAt` *has an* `onInsert` *property, which returns a callback that will set it to the current timestamp whenever a new document is inserted."*
There isn't an `onInsert` property listed in the schema.

<img width="188" alt="screen shot 2018-02-04 at 2 01 38 pm 2" src="https://user-images.githubusercontent.com/15968012/35777777-02d713ca-09b4-11e8-84ea-90e89054f600.png">

**Comment by SachaG** [comment]
Oh right, that's because `JSON.stringify` doesn't work on functions. I'll fix it.
