### ISSUE TITLE
Example-Forum New version - How to handle multiple category parameters ?

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#142]
Hi,

In the version <1.14, we use
http://localhost:3000/?cat=agro&cat=agroindus&cat=agtech
to display list of posts from category agro or category agroindus or category agtech

In the new version, I am trying
http://localhost:3000/category/agro?/agroindus?/agtech

and

http://localhost:3000/category/agro&cat=agroindus&cat=agtech

but both display a list of post from category agro ONLY.

What should I use ?

Thank You for your great works on Vulcan 1.14.

Adalidda

**Comment by adalidda** [comment]
In PostHome.jsx, I am also trying

  return <Components.PostsList input={{ search, filter: { _byCategory: { _in: ['agro','agroindus','agtech'] } },sort: { [getOrderProperty(currentRoute)]: 'desc' } }} />;


but got the following error:

[GraphQL error]: Message: Variable "$input" got invalid value { limit: 20, enableTotal: true, enableCache: false, filter: { _byCategory: [Object] }, sort: { score: "desc" } }; Field "_in" is not defined by type PostByCategoryFilterInput at value.filter._byCategory., Location: line 1, col 13, Path: undefined

**Comment by adalidda** [comment]
Finally, I make it work by using return { selector 
inside customFilters .

Love to see more examples in the doc section

input MovieFilterInput { 
 _and: [MovieFilterInput] 
 _not: MovieFilterInput  
_or: [MovieFilterInput]
  _id: String_Selector  
createdAt: Date_Selector  
userId: String_Selector  
slug: String_Selector  
title: String_Selector}

in particular example with _and, _or etc... I am a little bit confuse between the syntax of the new filter 
 (Vulcan >= 1.14) and the syntax of mongodb selector

Thank You
Adalidda

**Comment by eric-burel** [comment]
Closing as solved. You're right, documentation and examples will improve over time as this is a very recent update.
