### ISSUE TITLE
Field "_nin" is not defined by type String_Selector - Example Forum

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#165]
Hi,

the query with _in is implemented but the query with _nin seem not yet implemented.
If I try to use the syntax like in Hasura https://hasura.io/docs/1.0/graphql/manual/queries/query-filters.html#list-based-search-operators-in-nin

query {
  author(
    where: {name: {_nin: ["Justin","Sidney","April"]}}
  ) {
    id
    name
  }
}

I got the error Field "_nin" is not defined by type String_Selector 

PS: Congratulation for this new version. withMulti2 is much faster and the possibility to enable cache is really great !

Thank You
Adalidda

**Comment by trusktr** [comment]
Hello, please post code properly so people can read it and help you. See the [Markdown guide](https://guides.github.com/features/mastering-markdown/).

If you write

````
```js
if (true) foo()
```
````

the result is


```js
if (true) foo()
```
