### ISSUE TITLE
Strange Bug in Example Forum - PostsPage if use <Components.PostsList

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#166]
Hi,

I have change the PostsPage.jsx from:
          <Components.PostsCommentsThread postId={post._id} input={{ filter: { postId: { _eq: post._id } } }} />

to

          <Components.PostsCommentsThread postId={post._id} input={{ filter: { postId: { _eq: post._id } } }} />
          <Components.PostsList input={{ enableCache: false, sort: { appDeadLine: 'asc'}, limit: 5,filter:{ appDeadLine: {_gt: new Date()}}}} />

If on the PostsList, i click on the title I can view my post page with (example url):  http://localhost:3000/posts/rQwvebG5sbozeaxTW/programme-d-altair-pour-startups-logiciel-de-conception-a

But if I try to copy/paste the url 
http://localhost:3000/posts/rQwvebG5sbozeaxTW/programme-d-altair-pour-startups-logiciel-de-conception-a

to the browser navigation bar directly, I got error:
This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE

I can't explain why !

If I remove the line 
<Components.PostsList  input={{ enableCache: false, sort: { appDeadLine: 'asc'}, limit: 5,filter:{ appDeadLine: {_gt: new Date()}}}} />

and copy/paste the url to the browser navigation bar, everything is working.

So the issue is with <Components.PostsList but why ?

Thank You
Adalidda

**Comment by adalidda** [comment]
Hi,

This bug is fixed by running inside if (Meteor.isClient)

if (Meteor.isClient) {
    return (...)
}

**Comment by trusktr** [comment]
Can you close this issue if you've solved your problem?
