### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by yehudaRipple** [VulcanJS/Vulcan-Starter#172]
when running `npm start` I get the following error

[[[[[ ~/repos/vulcan/Vulcan-Starter ]]]]]     

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of getting-started satisfies all constraints: @=1.15.0,
   @=0.0.0
   Constraints on package "getting-started":
   * getting-started@=1.15.0 <- top level
   * getting-started@=0.0.0 <- top level
   
=> Your application has errors. Waiting for file change.

Meteor 1.10.2
Node.js v12.16.3

**Comment by eric-burel** [comment]
Just fixed, thanks
