### ISSUE TITLE
npm start fails - Cannot find module 'fibers/node_modules/fibers/node_modules/fs'

### ISSUE THREAD

**Issue by yehudaRipple** [VulcanJS/Vulcan-Starter#173]
After running npm start I get the following error:

W20200511-14:36:21.405(3)? (STDERR) internal/modules/cjs/loader.js:985
W20200511-14:36:21.425(3)? (STDERR)   throw err;
W20200511-14:36:21.425(3)? (STDERR)   ^
W20200511-14:36:21.425(3)? (STDERR) 
W20200511-14:36:21.426(3)? (STDERR) Error: Cannot find module 'fibers/node_modules/fibers/node_modules/fs'
W20200511-14:36:21.426(3)? (STDERR) Require stack:
W20200511-14:36:21.426(3)? (STDERR) - /home/.../.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js
W20200511-14:36:21.426(3)? (STDERR) - /home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/programs/server/boot.js
W20200511-14:36:21.426(3)? (STDERR) - /home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/main.js
W20200511-14:36:21.427(3)? (STDERR)     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
W20200511-14:36:21.427(3)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
W20200511-14:36:21.427(3)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1044:19)
W20200511-14:36:21.427(3)? (STDERR)     at require (internal/modules/cjs/helpers.js:77:18)
W20200511-14:36:21.427(3)? (STDERR)     at Object.<anonymous> (/home/.../.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js:4:11)
W20200511-14:36:21.428(3)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1158:30)
W20200511-14:36:21.428(3)? (STDERR)     at Module.Mp._compile (/home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/programs/server/runtime.js:50:23)
W20200511-14:36:21.428(3)? (STDERR)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
W20200511-14:36:21.428(3)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:1002:32)
W20200511-14:36:21.428(3)? (STDERR)     at Module.Mp.load (/home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/programs/server/runtime.js:15:31) {
W20200511-14:36:21.429(3)? (STDERR)   code: 'MODULE_NOT_FOUND',
W20200511-14:36:21.429(3)? (STDERR)   requireStack: [
W20200511-14:36:21.429(3)? (STDERR)     '/home/.../.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js',
W20200511-14:36:21.429(3)? (STDERR)     '/home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/programs/server/boot.js',
W20200511-14:36:21.429(3)? (STDERR)     '/home/.../repos/vulcan/Vulcan-Starter/.meteor/local/build/main.js'
W20200511-14:36:21.429(3)? (STDERR)   ]
W20200511-14:36:21.429(3)? (STDERR) }

**Comment by eric-burel** [comment]
Can you run commands using `meteor npm` instead of just npm? Sounds like a version issue, to be confirmed. Maybe also clean your node_modules

**Comment by yehudaRipple** [comment]
tried it and got the same error after running
`rm node_modules/ -rf`
`meteor npm i`

Would you also please explain what you mean by version issue?  My company deciding whether to use Vulcan and I would like to understand more.  Thank you.

**Comment by eric-burel** [comment]
You may want to get more info on Meteor itself then. Meteor recommends to call `meteor npm` because it guarantees that you run the same Node version as Meteor.
You can also install the correct version of Node on your machine too.

People on the Meteor forum could probably help better, it seems related to Meteor update, I could not reproduce

**Comment by yehudaRipple** [comment]
I reinstalled meteor and the error went away

**Comment by eric-burel** [comment]
Good to hear! Please close issues when they are fixed.
