### ISSUE TITLE
Getting-Started tutorial: Step 5 bug in text displayed 

### ISSUE THREAD

**Issue by robeastham** [VulcanJS/Vulcan-Starter#22]
After completing Step 5 the returned text says:

> Note that createdAt has an onInsert property, which returns a callback that will set it to the current timestamp whenever a new document is inserted. 

However the **_createdAt_** only appears in the actual source code and not in the inline version returned to the user the through the webpage. Dashing out the door now and wanted to log here. Will try and figure out why and send a pull request.

**Comment by SachaG** [comment]
Oh sorry about that, I changed that to use a plain text string to avoid these issues but it looks like I had forgotten to actually push. Can you check again now?

https://github.com/VulcanJS/Vulcan-Starter/blob/master/packages/getting-started/lib/components/other/Schema.jsx

**Comment by robeastham** [comment]
All good now after pulling and merging master. Thanks Sacha.
