### ISSUE TITLE
example-forum when filter by category and voteup, posts disappear from view

### ISSUE THREAD

**Issue by farjang** [VulcanJS/Vulcan-Starter#34]
**Steps to reproduce**
1. use example-form
2. assign a category to a post
3. filter by category
4. vote up

**Results:**
Posts disappear from view

**Expected Results:**
Posts should still be there

**Comment by SachaG** [comment]
I just removed the part of the code that was supposed to resort the list after a vote. It was probably confusing to have your post jump up or down the list anyway.
