### ISSUE TITLE
Example-Forum Vulcan 1.8.10 - Search do nothing with the word année

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#39]
Hi,

Today, I found a strange issue with search !
If I search with année the search do nothing.
If I search with the following, all are ok:
bonne année
bonne
opérateur
stratégie

So the issue is with the word année only (at least, issue found until now).

You can try it at https://fr.adalidda.com

Thank You
Adalidda

**Comment by SachaG** [comment]
Seems to work for me? I don't see any reason why a specific word wouldn't work.

**Comment by adalidda** [comment]
You are right, it's not a bug. The search functionality had been improved a lot, I didn't notice it.

Sorry.
Adalidda.
