### ISSUE TITLE
Seems to missing prestart_vulcan script

### ISSUE THREAD

**Issue by mzastue** [VulcanJS/Vulcan-Starter#4]
Hi, I think this repo is not fully prepared to creating your own build of vulcan project.
After cloning this repo on my local machine, first thing I do was of course `npm install` but then as VulcanJS main manual says next step is `npm start`, but it needs prestart_vulcan.

I think it could b copied from VulcanJs repo and prepared a little bit for moving example_settings.json to settings.json.

Cheers, good job any way ;)

**Comment by SachaG** [comment]
I don't think we need prestart_vulcan.sh, I'll remove it. Anyway this will be replaced by the CLI tool soon :)
