### ISSUE TITLE
Bugs with latest Vulcan-Starter

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#45]
Hi,

Bug 1: After running, npm install, I run npm start and got the following error:

/home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:475
W20180325-11:58:50.559(7)? (STDERR) }).run();
W20180325-11:58:50.560(7)? (STDERR)    ^
W20180325-11:58:50.561(7)? (STDERR) 
W20180325-11:58:50.561(7)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/objectSpread'
W20180325-11:58:50.561(7)? (STDERR)     at Function.Module._resolveFilename (module.js:538:15)
W20180325-11:58:50.562(7)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180325-11:58:50.562(7)? (STDERR)     at Object.require (/home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:288:32)
W20180325-11:58:50.563(7)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:651:18)
W20180325-11:58:50.563(7)? (STDERR)     at require (packages/modules-runtime.js:244:16)
W20180325-11:58:50.564(7)? (STDERR)     at livedata_connection.js (/home/kauprey/Vulcan-Starter/.meteor/local/build/programs/server/packages/ddp-client.js:149:45)
W20180325-11:58:50.564(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180325-11:58:50.564(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180325-11:58:50.565(7)? (STDERR)     at namespace.js (packages/ddp-client/common/namespace.js:1:300)
W20180325-11:58:50.565(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)

Bug 2: with Example-Forum
/home/kauprey/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180325-12:09:27.457(7)? (STDERR) 						throw(ex);
W20180325-12:09:27.457(7)? (STDERR) 						^
W20180325-12:09:27.458(7)? (STDERR) 
W20180325-12:09:27.458(7)? (STDERR) Error: "comments" is Array type but the schema does not include a "comments.$" definition for the array items"
W20180325-12:09:27.459(7)? (STDERR)     at checkAndScrubDefinition (/home/kauprey/Vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:1139:11)
W20180325-12:09:27.459(7)? (STDERR)     at /home/kauprey/Vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:593:9
W20180325-12:09:27.460(7)? (STDERR)     at Array.forEach (<anonymous>)
W20180325-12:09:27.460(7)? (STDERR)     at SimpleSchema.extend (/home/kauprey/Vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:578:30)
W20180325-12:09:27.461(7)? (STDERR)     at new SimpleSchema (/home/kauprey/Vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:138:10)
W20180325-12:09:27.461(7)? (STDERR)     at createCollection (packages/vulcan:lib/lib/modules/collections.js:120:29)

Thank You
Adalidda

**Comment by jorisroling** [comment]
+1

**Comment by SachaG** [comment]
Not sure about the first issue, but the second one is due to a recent version of SimpleSchema. I'll push a fix.

**Comment by jorisroling** [comment]
Still got the first issue: Error: Cannot find module '@babel/runtime/helpers/builtin/objectSpread'

**Comment by SachaG** [comment]
Is this when running the getting-started example?

**Comment by jorisroling** [comment]
This error happens when I `cd` to this project (Vulcan-Starter), initialise it with `npm install`, and start it by typing `npm start`. (all according to the README.md)

**Comment by adalidda** [comment]
The 2 Bugs are now fixed. 
Please update also lib/modules/posts/custom_fields.js
From
    fieldName: 'posts',
    fieldSchema: {
      type: Array,

To
    fieldName: 'posts',
    fieldSchema: {
      type: Object,

Thank You so much.
Adalidda

**Comment by valgalin** [comment]
@adalidda Thanks! That fixed the issue for me.
