### ISSUE TITLE
Getting-Started tutorial: Report and problems/solutions list 

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan-Starter#52]
````
meteor 1.6.1, node v8.9.4, osX 10.12.6
METEOR_PACKAGE_DIRS="---cut---/Vulcan/packages" meteor --port 3000 --settings settings.json
````
First error 
````
I20180501-11:38:44.417(2)? url:  /
I20180501-11:38:44.565(2)? { Error: // Component Step3 is not registered
I20180501-11:38:44.566(2)?     at Object.get (packages/vulcan:lib/lib/modules/components.js:16:13)
I20180501-11:38:44.566(2)?     at Object.step2 (packages/getting-started/lib/modules/checks.js:22:23)
I20180501-11:38:44.566(2)?     at Nav.React.createElement.React.createElement._.range.map.i (packages/getting-started/lib/components/other/Nav.jsx:22:20)
I20180501-11:38:44.567(2)?     at Array.map (<anonymous>)
I20180501-11:38:44.567(2)?     at Nav (packages/getting-started/lib/components/other/Nav.jsx:20:26)
...
W20180501-11:38:44.573(2)? (STDERR) 2018-05-01T09:38:44.418Z 'error while server-rendering' 
...
````
Solution : uncomment registerComponent in Step3.js then
````
 url:  /
I20180501-11:45:03.197(2)? { Error: // Component Step4 is not registered
I20180501-11:45:03.198(2)?     at Object.get (packages/vulcan:lib/lib/modules/components.js:16:13)
I20180501-11:45:03.198(2)?     at Object.step3 (packages/getting-started/lib/modules/checks.js:26:25)
I20180501-11:45:03.199(2)?     at Nav.React.createElement.React.createElement._.range.map.i (packages/getting-started/lib/components/other/Nav.jsx:22:20)
I20180501-11:45:03.199(2)?     at Array.map (<anonymous>)
I20180501-11:45:03.199(2)?     at Nav (packages/getting-started/lib/components/other/Nav.jsx:20:26)
...
````
Solution : uncomment import '../components/steps/Step4.jsx'; in components.js
--> ok now I can access to tutorial

At Step1 : "By the way, when developing locally you can review all your routes using the Routes dashboard. " with link to http://localhost:3000/routes , when you try to access this route 
````
I20180501-11:52:48.770(2)? url:  /routes
I20180501-11:52:48.802(2)? { Error: // Component undefined is not registered
I20180501-11:52:48.803(2)?     at Object.get (packages/vulcan:lib/lib/modules/components.js:16:13)
I20180501-11:52:48.804(2)?     at DatatableCell (packages/vulcan:core/lib/modules/components/Datatable.jsx:237:41)
....
````
No solution ...

At Step2 : "You can review them all by accessing the Components dashboard " with link to http://localhost:3000/components, same here where you try to access this route 
````
I20180501-12:08:32.653(2)? url:  /components
I20180501-12:08:32.656(2)? { Error: // Component undefined is not registered
I20180501-12:08:32.656(2)?     at Object.get (packages/vulcan:lib/lib/modules/components.js:16:13)
I20180501-12:08:32.656(2)?     at DatatableCell (packages/vulcan:core/lib/modules/components/Datatable.jsx:237:41)
...
````
No solution ...

At Step4, after uncommenting the ModalTrigger in Step4.js
````
I20180501-12:19:17.003(2)? url:  /step/4
I20180501-12:19:17.005(2)? { Error: // Component ModalTrigger is not registered
I20180501-12:19:17.005(2)?     at Object.get (packages/vulcan:lib/lib/modules/components.js:16:13)
I20180501-12:19:17.005(2)?     at Step4 (packages/getting-started/lib/components/steps/Step4.jsx:25:17)
....
````
Blocked ...
To be continued

**Comment by Apollinaire** [comment]
About the routes and component dashboards: you must have the debug package enabled.
Add one line to your .meteor/packages file: 
`vulcan:debug`
About the modal component, you must have the ui-bootstrap package, the ui components were very recently moved out of the core package, so the tutorial has not been updated yet. 
Adding the following line to your .meteor/packages file should solve it: 
`vulcan:ui-bootstrap`

**Comment by lc3t35** [comment]
Thank you @Apollinaire 
````
meteor add vulcan:debug                                                                                  
   vulcan:debug: Vulcan debug package            
meteor add vulcan:ui-bootstrap
 => Errors while parsing arguments:           
While adding package vulcan:ui-bootstrap:
error: no such package
````

**Comment by SachaG** [comment]
> Error: // Component Step3 is not registered

This was because I was testing some code on `devel` to tell you when you try to use an unregistered component, but it turned out to be a bad idea because the error was triggered even for checks for that component's existence (which the getting-started package uses). Shouldn't happen anymore.

**Comment by SachaG** [comment]
Btw you can switch your main Vulcan repo to `master` to get around these issues, the `devel` branch is always a little more unstable.

**Comment by lc3t35** [comment]
ISS to Osaka, at step10 now, everything is green, continuing the mission ...

**Comment by lc3t35** [comment]
step13 : login form has a strange look
![capture d ecran 2018-05-06 a 11 06 42](https://user-images.githubusercontent.com/921372/39671707-1820634c-511e-11e8-88c9-4ee2334d4fde.png)

**Comment by SachaG** [comment]
Great! Can I close this issue?

**Comment by lc3t35** [comment]
I'd rather like exposed Step17 "clones" problem to be explained before closing ;)

**Comment by SachaG** [comment]
I'm not sure about this bug. I was thinking I'd fix it when switching to Apollo v2.x. 

https://github.com/VulcanJS/Vulcan/issues/1951
