### ISSUE TITLE
Vulcan-Starter with errors on Chrome for example-instagram

### ISSUE THREAD

**Issue by kankando** [VulcanJS/Vulcan-Starter#55]
Vulcan-Starter example-instagram cannot be loaded and it seem to be caused by runtime error on Chrome as below.

![screen shot 2018-05-05 at 11 08 05](https://user-images.githubusercontent.com/4159477/39664689-85d62bfc-50b9-11e8-9249-cee209d3aa2f.png)

With 

Meteor 1.6.1
Node v10.0.0
Npm 5.6.0

As the result, the page cannot be loaded properly and picture cannot be loaded as below.

![screen shot 2018-05-05 at 11 12 40](https://user-images.githubusercontent.com/4159477/39664714-e6c6a0d6-50b9-11e8-9f3f-b29fe3adbe8a.png)

Hope someone could help with this.

**Comment by pozylon** [comment]
Same here, could not fix it yet

**Comment by kankando** [comment]
Maybe the team is now looking at it, give them a few more days or I have to switch to use other framework. Sigh.

**Comment by SachaG** [comment]
I fixed the issue with the missing photos. As for the error messages, it seems to be some kind of Meteor error, I'm not sure it's related to Vulcan directly. I'd suggest doing: 

- `git pull` to get the latest changes
- `meteor reset` to reset the project
- delete `node_modules` and then `npm install` again to reset node packages. 

Let me know if this works!

**Comment by pozylon** [comment]
Hey @SachaG thanks for some hints, I just went through the bulletpoints but it didn't help. And it's not an issue specific with the instagram example, these Uncaught Typerror's come up no matter with what packages you bring up the starter project. I have Node v8.11.1 installed and completely reinstalled Meteor from meteor.com

**Comment by kankando** [comment]
Thanks @SachaG but it sounds like still a blocker. Shall we raise it to https://forums.meteor.com/ for the group to look at? if it is sounds like due to the incompatible between meteor / node / npm?

Really love to use this framework but it have to be runnable, before we can code.....

**Comment by kankando** [comment]
I have raised this separately to meteor forum, see how it will go.
https://forums.meteor.com/t/is-it-problem-with-meteor-or-vulcanjs-or-something-else/43568

**Comment by SachaG** [comment]
Are you using the normal install or the 2-repo install?

**Comment by pozylon** [comment]
@SachaG Normal Install

**Comment by pozylon** [comment]
I just did some more research on this topic:

- The errors are browser-independent
- _this._launchConnection is referenced and this.launchConnection exists in the uncompiled version and cannot be unreferenced, but it seems like the compiled file is somehow corrupt

It could be one of those babel / ecmascript packages: 

meteor:ecmascript
meteor:ecmascript-runtime-client
@babel/runtime

Maybe related to https://github.com/meteor/meteor/blob/devel/History.md#v1611-2018-04-02 changes to @babel/runtime

**Comment by lc3t35** [comment]
no error for me OSX 10.12.6, meteor 1.6.1, node v8.9.4, npm 5.6.0, chrome 66.0.3359.139
![capture d ecran 2018-05-08 a 11 38 33](https://user-images.githubusercontent.com/921372/39750153-ca547052-52b4-11e8-8864-72a9fbaf1c18.png)

**Comment by lc3t35** [comment]
https://forums.meteor.com/t/upgraded-to-1-6-1-1-now-getting-all-kinds-of-console-errors/43462

**Comment by alabrazi** [comment]
Same problem with me on MacOS High Sierra

**Comment by SachaG** [comment]
I've only tested Vulcan with Meteor 1.6.1. Can you try downgrading?

**Comment by alabrazi** [comment]
My current version of Meteor is 1.6.1

**Comment by pozylon** [comment]
This will fix the above errors (basically a bump of npm packages, i think the one that matters is the babel runtime one):

https://gist.github.com/pozylon/2f42567ecdc47ad7cb1e64012d7c5a69

**Comment by vipinlahoti** [comment]
Thanks @pozylon it solved the issue

**Comment by SachaG** [comment]
Just pushed an update, let me know.

**Comment by kankando** [comment]
Thanks @pozylon  and @SachaG , Just need to git pull Vulcan-starter for latest master and it should do the magic without downgrading node or meteor?

**Comment by alabrazi** [comment]
Thanks, the last update solved the problem. Also, the Modal in step 4 is showing now.

**Comment by kankando** [comment]
Hello everyone, with the latest pull the getting-started able to start with only one warning which is fine.

![screen shot 2018-05-10 at 12 12 37](https://user-images.githubusercontent.com/4159477/39826345-ed6c2606-53e6-11e8-9bb3-b616a6d32d70.png)

But example-instagram still didnt work for me, with the following from the console and blank page show up.

![screen shot 2018-05-10 at 12 15 42](https://user-images.githubusercontent.com/4159477/39826452-53462bca-53e7-11e8-90cc-73ff7e154b86.png)

Do i need to downgrade the node?

```
Meteor 1.6.1.1
Node v10.0.0
Npm 5.6.0
```

or any package missing?

```
meteor list
accounts-password  1.5.1  Password support for accounts
example-instagram  0.0.0+
vulcan:core        1.10.0  Vulcan core package
vulcan:i18n-en-us  1.10.0  Vulcan i18n package 
```
@pozylon @SachaG @lc3t35 able to shed some light please?

**Comment by lc3t35** [comment]
when you switch between examples : meteor reset, meteor npm install, meteor --settings settings.json
don't forget to add METEOR_PACKAGE_DIRS if it's a 2 repo install.

**Comment by kankando** [comment]
Thanks a lot. it all about the node version 10.0.0 is not compatible and all good now once downgraded to Node 8.11.1. Please close.

https://forums.meteor.com/t/is-it-problem-with-meteor-or-vulcanjs-or-something-else/43568/5
