### ISSUE TITLE
Default package installed by default with npm install

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#67]
Hi,

I may be wrong but I think that the default packages install with npm install are not the same in Vulcan-starter and in Vulcan. Could you check that ? Seem the default package install with vulcan-starter is much completed !

Could you include meteor npm install @babel/runtime@latest into the default package to be installed with npm install ? That avoid new comer to meet issue that they don't know how to resolve.

Thank You
Adalidda

**Comment by SachaG** [comment]
That's possible, but there is never a reason why you'd need to run `npm install` inside the main Vulcan repo. Still I agree it'd be better to keep the packages in sync, I'd accept a PR to fix that.

**Comment by eric-burel** [comment]
Vulcan package.json is usually the reference, but we try to keep both in sync as much as possible.

When having issues with Babel you usually need to reinstall using `meteor npm i`, let us know if you have more precise errors.
