### ISSUE TITLE
Step 18 - sorting doesnt work

### ISSUE THREAD

**Issue by jesperordrup** [VulcanJS/Vulcan-Starter#74]
When uncommenting the following code the movielist should sort alfabetically. It doesnt. The sorting remains unchanged (createdAt).

```
import Movies from './collection.js';

// Uncomment on #Step18:
Movies.addView('alphabetical', terms => ({
  options: {
    sort: {name: 1}
  }
}));
```

No errors in console on server or client.
Code is run (added a console.log statement)

**Comment by eric-burel** [comment]
Step is updated, feel free to reopen
