### ISSUE TITLE
Starter Step 17

### ISSUE THREAD

**Issue by dakratz** [VulcanJS/Vulcan-Starter#88]
The new and edit buttons for films do not work.

New will give the following error after submitting the form:
Network error: NetworkError when attempting to fetch resource.

Edit will return what looks to be a mongodb id, and then eventually a blank form.

**Comment by SachaG** [comment]
It seems to work for me. Can you open your browser devtool's network tab and see what the GraphQL request returns?

**Comment by eric-burel** [comment]
Could not repro, feel free to reopen an issue if it happens again
