### ISSUE TITLE
Data Not sorted in example-movies

### ISSUE THREAD

**Issue by mrumaiz** [VulcanJS/Vulcan-Starter#91]
Movies list in example-movies package is not sorted. According to documentation [Vulcan](http://docs.vulcanjs.org/example-movies.html#
![vulcan-starter]  is sorting is done in this package 
(https://user-images.githubusercontent.com/14245012/45817750-58f50300-bcfd-11e8-898f-4099f49cbc10.PNG)
Sorting)

**Comment by Apollinaire** [comment]
Hi @mrumaiz, in the movies-example package the movies are **sorted by year**, as your screenshot shows. The code is here : https://github.com/VulcanJS/Vulcan-Starter/blob/master/packages/example-movies/lib/modules/movies/parameters.js
By default Vulcan sorts data by date of creation (`createdAt` field). To see the difference, go to `example-movies/lib/modules/movies/parameters.js and comment the last line.
Try adding some movies with the form on top of the page, and make the year vary to make sure the sorting is correctly working. If it's not working, make sure you are on the latest version of the vulcan-starter by git-pulling this repository. This package has been updated lately and you might be on an older version if you cloned this more than a month ago.
Hope you enjoy the framework as much as I do!

**Comment by mrumaiz** [comment]
Thank You @Apollinaire .
